name: 42Cursus C/CPP Makefile Test

description: This workflow finds Makefiles in the repository and runs 'make' in each directory

branding:
  icon: 'check-circle'
  color: 'green'

on: push

inputs:
  dir:
    description: 'The directory to search for Makefiles'
    default: .

runs:
  using: 'composite'
  shell: bash
  steps:
    - uses: actions/checkout@v3
    - run: |
        set -e
        for makefile in $(find ${{ inputs.dir }} -type f -name "Makefile"); do
          cd "$(dirname "$makefile")"
          make
          if [ $? -ne 0 ]; then
            echo "Make failed in $(dirname "$makefile"). Exiting workflow."
            exit 1
          fi
          cd -
        done
